-- DeviceGuide 3D 预览字段：保底手工脚本（若 GORM AutoMigrate 未生效时使用）
-- 幂等：使用 INFORMATION_SCHEMA 判断列是否存在再新增。

SET @db := DATABASE();

-- model3dEnabled BOOL DEFAULT 0
SET @has := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='device_guides' AND COLUMN_NAME='model3dEnabled');
SET @sql := IF(@has=0, 'ALTER TABLE device_guides ADD COLUMN model3dEnabled TINYINT(1) NOT NULL DEFAULT 0', 'SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- model3dUrl VARCHAR(500)
SET @has := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='device_guides' AND COLUMN_NAME='model3dUrl');
SET @sql := IF(@has=0, "ALTER TABLE device_guides ADD COLUMN model3dUrl VARCHAR(500) NOT NULL DEFAULT ''", 'SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- model3dDecalUrl VARCHAR(500)
SET @has := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='device_guides' AND COLUMN_NAME='model3dDecalUrl');
SET @sql := IF(@has=0, "ALTER TABLE device_guides ADD COLUMN model3dDecalUrl VARCHAR(500) NOT NULL DEFAULT ''", 'SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- model3dSkyboxUrl VARCHAR(500)
SET @has := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@db AND TABLE_NAME='device_guides' AND COLUMN_NAME='model3dSkyboxUrl');
SET @sql := IF(@has=0, "ALTER TABLE device_guides ADD COLUMN model3dSkyboxUrl VARCHAR(500) NOT NULL DEFAULT ''", 'SELECT 1');
PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
